using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

[assembly: AssemblyDescription("")]
[assembly: ComVisible(true)]
// Product/company/title/version attributes are generated by Directory.Build.targets.
[module: SuppressIldasm]
