using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

[assembly: AssemblyDescription("Подходит для SolidWorks 2012 и выше")]
[assembly: Guid("307e049d-dea2-4a8a-ac72-13757d61fe5d")]
[assembly: ComVisible(false)]
// Product/company/title/version attributes are generated by Directory.Build.targets.
